// <auto-generated />
using MataFomeAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MataFomeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220603000209_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("MataFomeAPI.Models.Item", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imagem")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.HasKey("Codigo");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MataFomeAPI.Models.Pedido", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF_Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("MataFomeAPI.Models.PedidoItens", b =>
                {
                    b.Property<int>("Codigo_Item")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("MataFomeAPI.Models.Usuario", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Saldo")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("CPF");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            CPF = "15468614677",
                            Cargo = "Gerente",
                            Email = "cardososavio5@gmail.com",
                            Nome = "Sávio Cardoso",
                            Saldo = 0.0,
                            Senha = "gerente@123"
                        },
                        new
                        {
                            CPF = "86264702072",
                            Cargo = "Vendedor",
                            Email = "savioshippuden13@gmail.com",
                            Nome = "João Gomes",
                            Saldo = 0.0,
                            Senha = "vendedor@123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
